# Generated by Django 3.2.9 on 2021-11-09 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('base_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0)])),
                ('description', models.CharField(max_length=128)),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0)])),
                ('category', models.CharField(max_length=32)),
            ],
        ),
    ]
